server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
  app:
    frontend:
      reset-password-url: ${FRONTEND_RESET_PASSWORD_URL}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
zalopay:
  appid: ${ZALOPAY_APPID}
  key1: ${ZALOPAY_KEY1}
  key2: ${ZALOPAY_KEY2}
  endpoint: ${ZALOPAY_ENDPOINT}
  callback-url: ${ZALOPAY_CALLBACK_URL}
  redirect-url: ${ZALOPAY_REDIRECT_URL}
logging:
  level:
    dev.langchain4j: DEBUG
    com.example.jewelry_management: DEBUG
    org.hibernate.type: TRACE