server:
  address: 0.0.0.0
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jewelry_management
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
  app:
    frontend:
      reset-password-url: http://127.0.0.1:5500/reset-password.html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: toducbn@gmail.com
    password: dhzeqmczmhevigrs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
zalopay:
  appid: 553
  key1: 9phuAOYhan4urywHTh0ndEXiV3pKHr5Q
  key2: Iyz2habzyr7AG8SgvoBCbKwKi3UzlLi3
  endpoint: https://sb-openapi.zalopay.vn/v2/create
  callback-url: http://localhost:8080/payment/zalopay/callback
  redirect-url: http://localhost:5500/order-success.html
logging:
  level:
    org:
      hibernate:
        type: trace
