spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jewelry_management
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace